services:
  - type: web
    name: my-flask-app  # replace with your service name
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"  # assuming your file is named app.py
    healthCheckPath: "/"
    autoDeploy: true