services:
  - type: web
    name: vitamin-recommender
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: "3.9.13"